version: '3.3'
services:
  mysql:
    container_name: mysql
    restart: always
    volumes:
      - '/Users/huibaoqi/opt/config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
      - '/Users/huibaoqi/out/mysql/:/out/mysql/'
      - '/etc/localtime:/etc/localtime'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=HBQ521521cf*'
    image: biarms/mysql:5.7.30-linux-arm64v8
  mysql8:
    container_name: mysql8
    restart: always
    volumes:
      - '/Users/huibaoqi/opt/config/mysqld8.cnf:/etc/my.cnf'
      - '/Users/huibaoqi/out/mysql8/:/out/mysql8/'
      - '/Users/huibaoqi/Documents/project/dbscripts:/out/mysql8/dbscripts'
      - '/etc/localtime:/etc/localtime'
    ports:
      - '3308:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=HBQ521521cf*'
    image: mysql/mysql-server:8.0.27
  shardingsphere-proxy:
    container_name: sharding
    restart: always
    volumes:
      - '/Users/huibaoqi/opt/sharding/conf:/opt/shardingsphere-proxy/conf'
      - '/Users/huibaoqi/opt/sharding/ext-lib:/opt/shardingsphere-proxy/ext-lib'
    environment:
      - PORT=3308
    ports:
      - '13308:3308'
    image: 'apache/shardingsphere-proxy:latest'
  redis:
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - '/Users/huibaoqi/opt/config/redis.conf:/etc/redis/redis.conf'
      - '/Users/huibaoqi/out/data:/data'
    command: redis-server /etc/redis/redis.conf --requirepass HBQ521521cf* --appendonly yes
    image: redis:5.0.3
  mongo:
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    image: mongo
  nginx:
    container_name: nginx
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - '/Users/huibaoqi/opt/config/nginx.conf:/etc/nginx/nginx.conf'
      - '/Users/huibaoqi/out/ui:/etc/nginx/out/ui'
    image: nginx:1.13
  hui:
    container_name: hui
    restart: always
    ports:
      - '81:8080'
    environment:
      - 'REFRESH_TOKEN=10846b5dbc3a42809b204e45aea6eb49'
    image: baoqihui/aliyundrive-webdav:arm
  clickhouse-server:
    container_name: ch-server
    restart: always
    ports:
      - '8123:8123'
      - '9009:9009'
      - '9090:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    image: 'yandex/clickhouse-server:22.1.2.2'