version: '3.3'
services:
  hui:
    container_name: hui
    restart: always
    ports:
      - '81:8080'
    environment:
      - 'REFRESH_TOKEN=10846b5dbc3a42809b204e45aea6eb49'
    image: baoqihui/aliyundrive-webdav:amd
  mysql:
    container_name: mysql
    restart: always
    volumes:
      - 'D:\opt\config\mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
      - 'D:\out\mysql\:/out/mysql/'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=HBQ521521cf*'
    image: mysql:5.7.29
  shard:
    image: apache/shardingsphere-proxy:5.1.0
    container_name: shard
    ports:
      - "3307:3307"
    volumes:
      - D:\opt\sharding\conf:/opt/shardingsphere-proxy/conf
      - D:\opt\sharding\ext-lib:/opt/shardingsphere-proxy/ext-lib
  redis:
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - 'D:\opt\config\redis.conf:/etc/redis/redis.conf'
    command: redis-server /etc/redis/redis.conf --requirepass HBQ521521cf* --appendonly yes
    image: redis:5.0.3
  clickhouse-server:
    container_name: ch-server
    restart: always
    ports:
      - '8123:8123'
      - '9009:9009'
      - '9090:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    image: 'yandex/clickhouse-server:22.1.2.2'
#  mysql8:
#    container_name: mysql8
#    restart: always
#    volumes:
#      - 'D:\opt\config\mysqld8.cnf:/etc/mysql/conf.d/mysql.cnf'
#      - 'D:\out\mysql8\:/out/mysql8/'
#    ports:
#      - '3308:3306'
#    environment:
#      - 'MYSQL_ROOT_PASSWORD=HBQ521521cf*'
#    image: mysql:8.0.27
#  redis:
#    container_name: redis
#    restart: always
#    ports:
#      - '6379:6379'
#    volumes:
#      - '/opt/config/redis.conf:/etc/redis/redis.conf'
#      - '/out/data:/data'
#    command: redis-server /etc/redis/redis.conf --requirepass HBQ521521cf* --appendonly yes
#    image: redis:5.0.3
#  mongo:
#    container_name: mongo
#    restart: always
#    ports:
#      - '27017:27017'
#    image: mongo
