version: '3.3'
services:
  mysql:
    container_name: mysql
    restart: always
    volumes:
      - '/opt/config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
      - '/out/mysql/:/out/mysql/'
      - '/etc/localtime:/etc/localtime'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=HBQ521521cf*'
    image: biarms/mysql:5.7.30-linux-arm64v8
  mysql7:
    container_name: mysql7
    restart: always
    volumes:
      - '/opt/config/mysqld7.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
      - '/out/mysql7/:/out/mysql7/'
      - '/etc/localtime:/etc/localtime'
    ports:
      - '3307:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=HBQ521521cf*'
    image: biarms/mysql:5.7.30-linux-arm64v8
  mysql8:
    container_name: mysql8
    restart: always
    volumes:
      - '/opt/config/mysqld8.cnf:/etc/my.cnf'
      - '/out/mysql8/:/out/mysql8/'
      - '/etc/localtime:/etc/localtime'
    ports:
      - '3308:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=HBQ521521cf*'
    image: mysql/mysql-server:8.0.27
  redis:
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - '/opt/config/redis.conf:/etc/redis/redis.conf'
      - '/out/data:/data'
    command: redis-server /etc/redis/redis.conf --requirepass HBQ521521cf* --appendonly yes
    image: redis:5.0.3
  mongo:
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    image: mongo
  minio:
    container_name: minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - '/opt/minio/data:/data'
      - '/opt/minio/config:/root/.minio'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=HBQ521521cf*
    command: server /data --console-address ":9001" --address ":9000"
    image: minio/minio
  nginx:
    container_name: nginx
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - '/opt/config/nginx.conf:/etc/nginx/nginx.conf'
      - '/opt/cert:/etc/nginx/cert'
      - '/opt/minio/data/dev-ui:/etc/nginx/dev-ui'
    image: nginx:1.13
  alist:
    container_name: alist
    restart: always
    volumes:
      - '/opt/alist:/opt/alist/data'
    ports:
      - '5244:5244'
    image: xhofe/alist:latest
  ql:
    container_name: ql
    restart: always
    volumes:
      - /opt/ql/data:/ql/data
    ports:
      - "87:5700"
    image: whyour/qinglong
  speedtest:
    container_name: speed
    restart: always
    ports:
      - '88:80'
    image: stilleshan/speedtest-x
  hui:
    container_name: hui
    restart: always
    ports:
      - '81:8080'
    environment:
      - 'REFRESH_TOKEN=10846b5dbc3a42809b204e45aea6eb49'
    image: baoqihui/aliyundrive-webdav:arm
  xue:
    container_name: xue
    restart: always
    ports:
      - '82:8080'
    environment:
      - 'REFRESH_TOKEN=24c20b7b68374f2e9e60eb22bdf7c491'
    image: baoqihui/aliyundrive-webdav:arm
  status:
    container_name: status
    restart: always
    ports:
      - '83:80'
      - '35601:35601'
    volumes:
      - '/opt/config/status.json:/ServerStatus/server/config.json'
    image: stilleshan/serverstatus
  halo:
    container_name: halo
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - '/opt/halo:/root/.halo'
    image: halohub/halo